// Generated by Wrangler on Thu Aug 08 2024 17:40:31 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

import type { R2Bucket } from '@cloudflare/workers-types';

export interface Env {
	ACCESS_KEY_ID: string;
	ACCOUNT_ID: string;
	BUCKET_NAME: string;
	FIREPROOF_SERVICE_PRIVATE_KEY: string;
	POSTMARK_TOKEN: string;
	SECRET_ACCESS_KEY: string;
	SERVICE_ID: string;
	MY_BUCKET: R2Bucket;
}
