// Generated by Wrangler on Fri Jul 26 2024 10:52:24 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	ACCESS_KEY_ID: string;
	ACCOUNT_ID: string;
	BUCKET_NAME: string;
	FIREPROOF_SERVICE_PRIVATE_KEY: string;
	MY_BUCKET: R2Bucket;
	POSTMARK_TOKEN: string;
	SECRET_ACCESS_KEY: string;
	SERVICE_ID: string;
}
