// Generated by Wrangler on Thu Jul 25 2024 22:02:20 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	BUCKET_NAME: "travis-fireproof-cars";
	SERVICE_ID: "did:key:z6Mkv7fM2mH4CkgWbiqmQCwUEJWHsR8EENsgPnm2UtmDeeDJ";
	ACCESS_KEY_ID: "945a5f685a2084960af89692250da0e7";
	ACCOUNT_ID: "cae1c33213e6c4d3093a01ae8a7e24b0";
	FIREPROOF_SERVICE_PRIVATE_KEY: string;
	SECRET_ACCESS_KEY: string;
	MY_BUCKET: R2Bucket;
}
